name: meow_ai
description: A cross-platform mobile application for offline cat breed recognition using AI

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.2.0+1
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  flutter_staggered_animations: ^1.1.1
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Camera & Image
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  image: ^4.1.3
  path_provider: ^2.1.1
  
  # Machine Learning
  tflite_flutter: ^0.10.4
  tflite_flutter_helper: ^0.3.1
  
  # Database & Storage
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Authentication & Cloud
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  
  # Localization
  intl: ^0.18.1
  
  # Networking
  http: ^1.1.0
  dio: ^5.3.4
  
  # Utils
  path: ^1.8.3
  permission_handler: ^11.1.0
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  
  # AR (Optional)
  arcore_flutter_plugin: ^0.0.9
  
  # Accessibility
  flutter_tts: ^3.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/images/
    - assets/models/
    - assets/icons/
    - assets/animations/
    - assets/data/

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700