name: meow_ai
description: A cross-platform mobile application for offline cat breed recognition using AI

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.2.0+1
  lottie: ^3.3.0
  cached_network_image: ^3.3.0
  flutter_staggered_animations: ^1.1.1
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Camera & Image
  camera: 0.10.5+9  # Updated to support Android namespace
  image_picker: ^1.0.4
  image: ^3.3.0
  path_provider: ^2.0.15
  
  # Machine Learning (disabled due to Android namespace compatibility issues)
  # tflite_flutter: ^0.9.0  # Namespace conflicts prevent compilation
  
  # Database & Storage
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Authentication & Cloud (updated for iOS compatibility)
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  
  # Localization
  intl: 0.20.2
  
  # Networking
  http: ^1.1.0
  dio: ^5.3.4
  
  # Utils
  json_annotation: ^4.9.0
  path: ^1.8.3
  permission_handler: ^12.0.1
  url_launcher: ^6.2.1
  share_plus: ^11.1.0
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.1
  
  # Notifications
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  
  # AR (temporarily disabled for iOS compatibility)
  # arcore_flutter_plugin: ^0.1.0
  
  # Accessibility
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  json_annotation: ^4.9.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^6.0.0
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

dependency_overrides:
  # Override conflicting packages for compatibility as recommended
  # Updated for Android namespace compatibility
  ffi: ^2.0.1
  image: ^3.3.0
  # Removed camera override to allow proper version resolution
  # tflite_flutter: ^0.10.0
  # tflite_flutter_helper: ^0.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  # Assets - Comprehensive declaration for Flutter asset bundling
  # Note: Large binary files (like TensorFlow Lite models) require explicit declaration
  assets:
    # Model files (explicit declaration for large binary assets)
    - assets/models/model.tflite
    - assets/models/labels.txt
    - assets/models/model_info.json
    - assets/models/
    
    # Data files
    - assets/data/comprehensive_cat_breeds.json
    - assets/data/enhanced_breeds.json
    - assets/data/
    
    # Image directories
    - assets/images/
    - assets/images/breeds/
    
    # Other asset directories
    - assets/icons/
    - assets/animations/

  # Fonts (using system fonts for now)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700